llm_provider: google
backend_url: https://generativelanguage.googleapis.com/v1
deep_think_llm: gemini-2.0-flash
quick_think_llm: gemini-2.0-flash
max_debate_rounds: 1
online_tools: true

binance:
  api_key: "df14774f6d3004a49ab0e26cc65b755b7c3c95951aa84b62541882d3d7de8b2c"
  api_secret: "2c7bf4928b44b3ccf9496c965cab9eb36aff50bf4918210ac6a70470a49d4dd4"
  symbol: "BTCUSDT"
  testnet: true

